version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - learn2reid
  ignore:
  - dependency-name: "@commitlint/load"
    versions:
    - 11.0.0
    - 12.0.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.1.0
    - 7.2.0
    - 8.0.0
  - dependency-name: "@commitlint/lint"
    versions:
    - 11.0.0
    - 12.0.0
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
