before_script:
  - npm install

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

test:node:4:
    image: node:4
    script:
        - npm test

test:node:6:
    image: node:6
    script:
        - npm test

test:node:8:
    image: node:8
    script:
        - npm test
