.npm_setup: &npm_setup |
  # update npm and install dependencies with `npm ci`
  npm i -g npm
  npm ci

test:node:6:
  image: node:6-alpine
  before_script:
    - *npm_setup
  script:
    - npm test
  after_script:
    - npm run report
  artifacts:
    paths:
      - coverage/

test:node:8:
  image: node:8-alpine
  before_script:
    - *npm_setup
  script:
    - npm test

pages:
  image: alpine:latest
  stage: deploy
  dependencies:
    - test:node:6
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
