name: Integration

on:
  push:
    branches:
      - main
  pull_request:

env:
  FORCE_COLOR: 2
  NODE_VERSION: 16
  NPM_VERSION: 8

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Update npm
        run: npm i -g npm@${{ env.NPM_VERSION }}
      - uses: actions/cache@v2
        id: node-cache
        with:
          path: |
            ~/.npm
            node_modules
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install 📦
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: ESLint ✨
        run: npm run eslint

  test:
    name: Test | Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Update npm
        run: npm i -g npm@${{ env.NPM_VERSION }}
      - uses: actions/cache@v2
        id: node-cache
        with:
          path: |
            ~/.npm
            node_modules
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install 📦
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test 🧪
        run: npm run test
