name: Integration

on:
  push:
    branches:
      - main
  pull_request:

env:
  FORCE_COLOR: 2
  NODE_VERSION: 14
  NPM_VERSION: 8

jobs:
  # eslint:
  #   name: ESLint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}
  #         cache: "npm"
  #         cache-dependency-path: "**/package-lock.json"
  #     - name: Update npm
  #       run: npm i -g npm@${{ env.NPM_VERSION }}
  #     - name: Install 📦
  #       run: npm install
  #     - name: ESLint ✨
  #       run: npm run lint:es

  test:
    name: Test | Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Update npm
        run: npm i -g npm@${{ env.NPM_VERSION }}
      - name: Install 📦
        run: npm install
      - name: Test 🧪
        run: npm run test
