name: Publish with Lerna

on: [workflow_dispatch]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: NPM install 📦
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lerna bootstrap 👢
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm run lerna -- bootstrap
      - name: Test 🧪
        run: npm test
      - name: Publish 🚀
        run: npm run lerna -- publish --yes --conventional-commits --create-release github
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
