name: Github Pages

on:
  push:
    branches:
    - main
    paths:
    - 'guides-website/**'
  workflow_dispatch:
    branches:
    - main
    paths:
    - 'guides-website/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install 📦
        working-directory: guides-website
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build docs 📄
        working-directory: guides-website
        run: npm run build
        env:
          BASE_URL: /style/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public

